name: Deployment

on:
  push:
    branches: [main, dev]

jobs:
  
    dev_deployment:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: build lambdas
        run: make packageLambdas
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: cd terraform && terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
          

      - run: cd terraform && terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
        
      - run: cd terraform && terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
  


  prod_deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: build lambdas
        run: make packageLambdas
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: cd terraform && terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
          
      - run: cd terraform && (terraform workspace new prod || true) && terraform workspace select prod && terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
        
      - run: cd terraform && (terraform workspace new prod || true) && terraform workspace select prod && terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}